[tool.poetry]
name = "django-10"
version = "0.1.0"
description = ""
authors = ["Oiseauoui <oiseua@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
